### ISSUE TITLE
Profile Card UI Enhancements & Interactive Features Added

### ISSUE THREAD

**Issue by harshpareshbhaigosalya** [muskanchoudhary001/Profile_Card#2]
Issue Description:

I have made the following enhancements and improvements to the profile card project. These changes include UI/UX enhancements, interactivity, and responsiveness, making the card more visually appealing and functional.

Changes Made:
1) UI Improvements:-
Refined the overall design layout with subtle shadow effects and hover transitions, making the card more dynamic and engaging for users.
Added hover effects to the social media icons and buttons, enhancing the user experience.
Improved the overall responsiveness of the profile card for various screen sizes, ensuring it works seamlessly on mobile and desktop devices.

2)Interactive Analytics Section:-
Implemented an interactive likes, comments, and shares system where users can click on the icons, and the counts will dynamically increase.
Added a hover effect on the analytics icons to make them more intuitive and interactive.

3)Functionality Enhancements:-
Added JavaScript functionality to handle like, comment, and share actions, updating the analytics section in real-time to enhance user engagement.
The likePost(), commentPost(), and sharePost() functions were introduced, allowing the counts to be incremented upon user interaction.

4)Code Structure & Comments:-
Refactored the code to improve readability and maintainability by adding comments throughout the HTML, CSS, and JavaScript sections, explaining key changes and functionality.
Ensured a more semantic structure for HTML, improving accessibility and search engine optimization (SEO).
![Screenshot 2024-10-02 120753](https://github.com/user-attachments/assets/3c5af418-8ad9-40bb-a9e2-954990406e06)
![Screenshot 2024-10-02 120853](https://github.com/user-attachments/assets/2b76f1ff-c2a8-484d-a2a8-8991c71c222a)

Request:
As this enhancement significantly improves the UI/UX, responsiveness, and interactivity of the profile card, I would like to request that these changes be accepted under Hacktoberfest 2024. These contributions align with the goals of Hacktoberfest by improving an open-source project and making meaningful enhancements.

Why This Should Be Accepted:-
Improved User Experience: The updated UI design and interactive features create a more engaging experience for users, leading to increased user interaction.
Better Responsiveness: The project now scales better across devices, making it accessible to a wider audience.
New Features: The like, comment, and share functionality adds real value by turning the static profile card into an interactive component.
I hope these contributions will be valuable to the project and contribute meaningfully to the open-source community as part of Hacktoberfest 2024.

Thank you for your time and consideration!

**Comment by muskanchoudhary001** [comment]
Hi @harshpareshbhaigosalya,

Thank you for the amazing work on the profile card enhancements. Could you please open a pull request with the changes so that I can review and merge it into the project?

Your contributions will be a great addition, and I look forward to accepting them for Hacktoberfest 2024.

Best,  
Muskan Choudhary !!

**Comment by muskanchoudhary001** [comment]
Before merging your changes, I would like to request a few adjustments related to the appearance of the **like**, **comment**, and **share** functionalities:

1. **Color Adjustments:**
   - Could you make the icons (like, comment, share) stand out a bit more by changing their colors when hovered? Perhaps using a bolder color (e.g., blue for likes, green for shares, etc.) to differentiate their state would enhance the user experience.

2. **Appearance Changes:**
   - The current hover effect is nice, but could you also add a slight scaling effect (e.g., increasing the size by 5%) when the user hovers over these icons? This will make the interactions feel more dynamic.
   - It would also be great if the counters (for likes, comments, and shares) had a smooth transition effect when updated, so the changes appear more fluid.

These adjustments would make the card even more interactive and visually appealing for users. Let me know what you think!

Thanks again for your effort, and I look forward to seeing the updates! 😊🌟

**Comment by muskanchoudhary001** [comment]
done great job !! kudos !!

**Comment by harshpareshbhaigosalya** [comment]
Thank you!
Plz assign me tag for "hacktoberfest-accepted".

**Comment by muskanchoudhary001** [comment]
Done!!

**Comment by harshpareshbhaigosalya** [comment]
Thank you! If any further changes are needed, I’d be happy to assist.

**Comment by muskanchoudhary001** [comment]
For now it's all good !! Its been great connecting with you.
