### ISSUE TITLE
font must be in a line

### ISSUE THREAD

**Issue by Gamerking177** [muskanchoudhary001/Profile_Card#4]
![image](https://github.com/user-attachments/assets/0502160f-3b94-48ed-a24d-e9613c4d94ff)

assign me i will fix it

**Comment by muskanchoudhary001** [comment]
Also , try to change the color for the button instead of grey and also try some UI effects. With that try to add effects to components and also attach screenshots for demo of the changes you will be making with the PR.

**Comment by Gamerking177** [comment]
Ok ma'am

**Comment by Gamerking177** [comment]
@muskanchoudhary001 can i change home.html to index.html plss reply

**Comment by muskanchoudhary001** [comment]
what will it make a differenece !!!

**Comment by Gamerking177** [comment]
@muskanchoudhary001 server understand index.html

**Comment by muskanchoudhary001** [comment]
I guess it does not make any uch difference but do it for your convience.

**Comment by Gamerking177** [comment]
@muskanchoudhary001 maam why

**Comment by Gamerking177** [comment]
@muskanchoudhary001 closed my issue
